### ISSUE TITLE
Frontend path error

### ISSUE THREAD

**Issue by barthdamon** [HunterFortuin/react-redux-boilerplate#1]
Hey Hunter, using your boilerplate cause its awesome :)

Ran into this trying to run the app:

```
ERROR in ./frontend/scripts/main.js
Module build failed: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.extname (path.js:1429:5)
    at processText (/Users/MattBarth/Desktop/development/mad_glory/web/sample-dashboard/node_modules/xo/node_modules/eslint/lib/cli-engine.js:193:30)
    at CLIEngine.executeOnText (/Users/MattBarth/Desktop/development/mad_glory/web/sample-dashboard/node_modules/xo/node_modules/eslint/lib/cli-engine.js:686:26)
    at Object.exports.lintText (/Users/MattBarth/Desktop/development/mad_glory/web/sample-dashboard/node_modules/xo/index.js:115:16)
    at lint (/Users/MattBarth/Desktop/development/mad_glory/web/sample-dashboard/node_modules/xo-loader/index.js:7:15)
    at Object.module.exports (/Users/MattBarth/Desktop/development/mad_glory/web/sample-dashboard/node_modules/xo-loader/index.js:90:3)
 @ multi main
```

I've made some server changes but no frontend changes yet. Any ideas why this might be?

**Comment by hunterfortuin** [comment]
Hm, not sure at a glance. I know the React ecosystem has been evolving super quickly. Try disabling the xo-loader for Webpack and see if that does anything.

I'll try to do a fresh install of the project this weekend and update anything that's out of date!

**Comment by barthdamon** [comment]
cool, where should I start to go about disabling that?

**Comment by hunterfortuin** [comment]
In the [webpack.config.dev.js](https://github.com/HunterFortuin/react-redux-boilerplate/blob/master/webpack.config.dev.js) file there's a preloader defined for `xo-loader`. Just remove that and you should be good to go!

If that doesn't do the trick you may have to remove the xo-loader npm module but IDT that's necessary.

**Comment by barthdamon** [comment]
That did it! Thanks dawg

**Comment by barthdamon** [comment]
whoops reopening cause forgot you are looking into it this weekend ;)
